"""

Revision ID: 6cccafeec009
Revises: 6b6164280364
Create Date: 2026-03-05 14:47:18.778209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6cccafeec009"
down_revision: Union[str, Sequence[str], None] = "6b6164280364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("alembic_version")
    op.add_column(
        "classrooms", sa.Column("total_capacity", sa.Integer(), nullable=False)
    )
    op.add_column(
        "classrooms", sa.Column("set_one_capacity", sa.Integer(), nullable=False)
    )
    op.add_column(
        "classrooms", sa.Column("set_two_capacity", sa.Integer(), nullable=False)
    )
    op.drop_column("classrooms", "capacity")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "classrooms",
        sa.Column("capacity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("classrooms", "set_two_capacity")
    op.drop_column("classrooms", "set_one_capacity")
    op.drop_column("classrooms", "total_capacity")
    # op.create_table(
    #     "alembic_version",
    #     sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
    # )
    # ### end Alembic commands ###
