"""

Revision ID: cd315957a26f
Revises: 6cccafeec009
Create Date: 2026-03-10 00:17:51.020978

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cd315957a26f"
down_revision: Union[str, Sequence[str], None] = "6cccafeec009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seatings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seating_arrangement", sa.JSON(), nullable=False),
        sa.Column("exam_name", sa.String(length=255), nullable=False),
        sa.Column("exam_time", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seatings")),
        schema="public",
    )
    op.create_index(
        op.f("ix_seatings_public_seatings_created_at"), "seatings", ["created_at"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_seatings_public_seatings_is_active"), "seatings", ["is_active"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_seatings_public_seatings_updated_by"), "seatings", ["updated_by"], unique=False, schema="public"
    )
    # op.drop_table("alembic_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "alembic_version",
    #     sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
    # )
    op.drop_index(op.f("ix_seatings_public_seatings_updated_by"), table_name="seatings", schema="public")
    op.drop_index(op.f("ix_seatings_public_seatings_is_active"), table_name="seatings", schema="public")
    op.drop_index(op.f("ix_seatings_public_seatings_created_at"), table_name="seatings", schema="public")
    op.drop_table("seatings", schema="public")
    # ### end Alembic commands ###
