"""

Revision ID: ea2484bd9786
Revises: cd315957a26f
Create Date: 2026-03-19 12:28:23.936992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ea2484bd9786"
down_revision: Union[str, Sequence[str], None] = "cd315957a26f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "SUPER_ADMIN", "VIEWER", name="role_enum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("name", name=op.f("uq_users_name")),
        schema="public",
    )
    op.create_index(op.f("ix_users_public_users_created_at"), "users", ["created_at"], unique=False, schema="public")
    op.create_index(op.f("ix_users_public_users_is_active"), "users", ["is_active"], unique=False, schema="public")
    op.create_index(op.f("ix_users_public_users_updated_by"), "users", ["updated_by"], unique=False, schema="public")
    # op.drop_table("alembic_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "alembic_version",
    #     sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
    # )
    op.drop_index(op.f("ix_users_public_users_updated_by"), table_name="users", schema="public")
    op.drop_index(op.f("ix_users_public_users_is_active"), table_name="users", schema="public")
    op.drop_index(op.f("ix_users_public_users_created_at"), table_name="users", schema="public")
    op.drop_table("users", schema="public")
    # ### end Alembic commands ###
