"""

Revision ID: 6b6164280364
Revises:
Create Date: 2026-02-05 17:40:25.379112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6b6164280364"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classrooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("classroom_name", sa.String(length=255), nullable=False),
        sa.Column("class_layout", sa.JSON(), nullable=False),
        sa.Column("columns_count", sa.Integer(), nullable=False),
        sa.Column("max_rows", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classrooms")),
        sa.UniqueConstraint(
            "classroom_name", name=op.f("uq_classrooms_classroom_name")
        ),
        schema="public",
    )
    op.create_index(
        op.f("ix_classrooms_public_classrooms_created_at"),
        "classrooms",
        ["created_at"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_classrooms_public_classrooms_is_active"),
        "classrooms",
        ["is_active"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_classrooms_public_classrooms_updated_by"),
        "classrooms",
        ["updated_by"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_classrooms_public_classrooms_updated_by"),
        table_name="classrooms",
        schema="public",
    )
    op.drop_index(
        op.f("ix_classrooms_public_classrooms_is_active"),
        table_name="classrooms",
        schema="public",
    )
    op.drop_index(
        op.f("ix_classrooms_public_classrooms_created_at"),
        table_name="classrooms",
        schema="public",
    )
    op.drop_table("classrooms", schema="public")
    # ### end Alembic commands ###
