"""add is_printed to seatings

Revision ID: 57ceaf3b7fb2
Revises: 70a301bdbd07
Create Date: 2026-06-15 04:40:37.550805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "57ceaf3b7fb2"
down_revision: Union[str, Sequence[str], None] = "70a301bdbd07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seatings",
        sa.Column(
            "is_printed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        schema="public",
    )

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("seatings", "is_printed", schema="public")